### ISSUE TITLE
Replace 'close' with 'settings'

### ISSUE THREAD

**Issue by Ingvord** [waltz-controls/waltz-grid-widget#7]
Please move settings icon to the header. Replace *delete* cross by it.

![Screenshot_20201218_141344_2](https://user-images.githubusercontent.com/11678364/102609174-191b6100-413c-11eb-83ef-9a4e0685ba41.png)

**Motivation:** as it is now settings are useless in terms of providing info, but consumes considerable amount of space

**Comment by kapot65** [comment]
Issue is outdated due to new interface #
